# Generated by Django 5.2 on 2025-04-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                ("No_Pokemon", models.IntegerField(primary_key=True, serialize=False)),
                ("Nombre", models.CharField(max_length=100, unique=True)),
                (
                    "Ruta_Imagen",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Descripcion", models.TextField(blank=True, null=True)),
                (
                    "Altura",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "Peso",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Pokémon",
                "verbose_name_plural": "Pokémon",
            },
        ),
    ]
