# Generated by Django 5.2 on 2025-04-29 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokedex", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre_Categoria", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.CreateModel(
            name="Generacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Juegos", models.CharField(max_length=100, unique=True)),
                ("Numero", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Generación",
                "verbose_name_plural": "Generaciones",
                "ordering": ["Numero"],
            },
        ),
        migrations.CreateModel(
            name="Grupo_Huevo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_huevo", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Grupo Huevo",
                "verbose_name_plural": "Grupos Huevo",
            },
        ),
        migrations.CreateModel(
            name="Habilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre_Habilidad", models.CharField(max_length=100, unique=True)),
                ("Descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Habilidad",
                "verbose_name_plural": "Habilidades",
            },
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre_Movimiento", models.CharField(max_length=100, unique=True)),
                ("Precision", models.IntegerField()),
                ("Potencia", models.IntegerField()),
                (
                    "Categoria",
                    models.CharField(
                        choices=[
                            ("Físico", "Físico"),
                            ("Especial", "Especial"),
                            ("Estado", "Estado"),
                        ],
                        max_length=50,
                    ),
                ),
                ("Puntos_Uso", models.IntegerField()),
            ],
            options={
                "verbose_name": "Movimiento",
                "verbose_name_plural": "Movimientos",
            },
        ),
        migrations.CreateModel(
            name="Tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre_Tipo", models.CharField(max_length=50, unique=True)),
                ("Color", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "verbose_name": "Tipo",
                "verbose_name_plural": "Tipos",
            },
        ),
        migrations.CreateModel(
            name="PokemonCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemon",
                        to="pokedex.categoria",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias",
                        to="pokedex.pokemon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Pokémon",
                "verbose_name_plural": "Categorías de Pokémon",
                "unique_together": {("pokemon", "categoria")},
            },
        ),
        migrations.CreateModel(
            name="PokemonGeneracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemon",
                        to="pokedex.generacion",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generaciones",
                        to="pokedex.pokemon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generación de Pokémon",
                "verbose_name_plural": "Generaciones de Pokémon",
                "unique_together": {("pokemon", "generacion")},
            },
        ),
        migrations.CreateModel(
            name="PokemonGrupoHuevo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grupo_huevo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemon",
                        to="pokedex.grupo_huevo",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupos_huevo",
                        to="pokedex.pokemon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo Huevo de Pokémon",
                "verbose_name_plural": "Grupos Huevo de Pokémon",
                "unique_together": {("pokemon", "grupo_huevo")},
            },
        ),
        migrations.CreateModel(
            name="PokemonHabilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("es_oculta", models.BooleanField(default=False)),
                (
                    "habilidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemon",
                        to="pokedex.habilidad",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habilidades",
                        to="pokedex.pokemon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habilidad de Pokémon",
                "verbose_name_plural": "Habilidades de Pokémon",
                "unique_together": {("pokemon", "habilidad")},
            },
        ),
        migrations.CreateModel(
            name="PokemonMovimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel_aprendizaje", models.IntegerField(blank=True, null=True)),
                (
                    "movimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemon",
                        to="pokedex.movimiento",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="pokedex.pokemon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Pokémon",
                "verbose_name_plural": "Movimientos de Pokémon",
                "unique_together": {("pokemon", "movimiento")},
            },
        ),
        migrations.CreateModel(
            name="PokemonTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos",
                        to="pokedex.pokemon",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemon",
                        to="pokedex.tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Pokémon",
                "verbose_name_plural": "Tipos de Pokémon",
                "unique_together": {("pokemon", "tipo")},
            },
        ),
    ]
