# Generated by Django 5.2 on 2025-04-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokedex", "0002_categoria_generacion_grupo_huevo_habilidad_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pokeball",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre_Pokeball", models.CharField(max_length=100, unique=True)),
                ("Descripcion", models.TextField(blank=True, null=True)),
                (
                    "Ruta_Imagen",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Ratio_Captura", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Pokéball",
                "verbose_name_plural": "Pokéballs",
            },
        ),
    ]
