# Generated by Django 5.2 on 2025-04-29 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pokedex", "0003_pokeball"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pokeball",
        ),
    ]
